package com.medibridge.entities.donar;

public enum MedicineCategory {
	ANTIBIOTIC, PAINKILLER, ANTIVIRAL, ANTIINFLAMMATORY, VITAMIN_SUPPLEMENT,
	ANTIFUNGAL, ANTACID, ANTIDIABETIC, ANTIALLERGIC, CARDIAC, HORMONAL, OTHER
}
